img = {
    colors: {
        "element": "102 85 61",
        "building": "102 60 88",
        "food": "61 62 102",
        "critter": "102 63 61",
        "geyser": "91 102 94",
        "plant": "69 102 61",
        "planet": "99 102 61",
        "other": "61 102 97"
    },
    elements: {
        "Abyssalite": "abyssalite",
        "Algae": "algae",
        "Aluminum Gas": "aluminum_g",
        "Aluminum Ore": "aluminum-ore",
        "Aluminum": "aluminum_s",
        "Bitumen": "bitumen",
        "Bleach Stone": "bleach_stone",
        "Brackene": "ice",
        "Brackwax": "brackwax",
        "Brine Ice": "brine_ice",
        "Brine": "brine",
        "Carbon Dioxide": "carbon_dioxide_g",
        "Carbon Gas": "carbon_g",
        "Ceramic": "ceramic",
        "Chlorine Gas": "chlorine_g",
        "Clay": "clay",
        "Coal": "coal",
        "Cobalt Gas": "cobalt_g",
        "Cobalt Ore": "cobalt-ore",
        "Cobalt": "cobalt_s",
        "Copper Gas": "copper_g",
        "Copper Ore": "copper-ore",
        "Copper": "copper_s",
        "Corium": "corium",
        "Crude Oil": "crude_oil_l",
        "Crushed Ice": "crushed_ice",
        "Crushed Rock": "crushed_rock",
        "Depleted Uranium": "depleted_uranium",
        "Diamond": "diamond",
        "Dirt": "dirt",
        "Electrum": "electrum",
        "Enriched Uranium": "enriched_uranium",
        "Ethanol Gas": "ethanol_g",
        "Ethanol": "ethanol_l",
        "Fertilizer": "fertilizer",
        "Fossil": "fossil",
        "Frozen Brackene": "ice",
        "Fullerene": "fullerene",
        "Genetic Ooze": "genetic_ooze",
        "Glass": "glass_s",
        "Gold Amalgam": "gold-amalgam",
        "Gold Gas": "gold_g",
        "Gold": "gold_s",
        "Granite": "granite",
        "Graphite": "graphite",
        "Hydrogen Gas": "hydrogen_g",
        "Ice": "ice",
        "Igneous Rock": "igneous_rock",
        "Insulite": "insulation",
        "Iron Gas": "iron_g",
        "Iron Ore": "iron-ore",
        "Iron": "iron_s",
        "Isoresin": "isoresin",
        "Lead Gas": "lead_g",
        "Lead": "lead_s",
        "Lime": "lime",
        "Liquid Carbon Dioxide": "carbon_dioxide_l",
        "Liquid Carbon": "carbon_l",
        "Liquid Chlorine": "chlorine_l",
        "Liquid Hydrogen": "hydrogen_l",
        "Liquid Methane": "methane_l",
        "Liquid Naphtha": "naphtha_l",
        "Liquid Nuclear Waste": "nuclear_waste",
        "Liquid Oxygen": "oxygen_l",
        "Liquid Phosphorus": "phosphorus_l",
        "Liquid Propane": "propane_l",
        "Liquid Resin": "resin_l",
        "Liquid Sucrose": "sucrose_l",
        "Liquid Sulfur": "liquid_sulfur",
        "Liquid Uranium": "uranium",
        "Mafic Rock": "mafic_rock",
        "Magma": "magma",
        "Molten Aluminum": "aluminum_l",
        "Molten Cobalt": "cobalt_l",
        "Molten Copper": "copper_l",
        "Molten Glass": "glass_l",
        "Molten Gold": "gold_l",
        "Molten Iron": "iron_l",
        "Molten Lead": "lead_l",
        "Molten Niobium": "niobium_l",
        "Molten Salt": "salt_l",
        "Molten Steel": "steel_l",
        "Molten Synthesis Gas": "",
        "Molten Tungsten": "tungsten_l",
        "Mud": "mud",
        "Natural Gas": "natural_gas",
        "Neutronium": "neutronium",
        "Niobium Gas": "niobium_g",
        "Niobium": "niobium_s",
        "Nuclear Fallout": "nuclear_fallout",
        "Obsidian": "obsidian",
        "Oxygen": "oxygen_g",
        "Oxylite": "oxylite",
        "Petroleum": "petroleum_l",
        "Phosphorite": "phosphorite",
        "Phosphorus Gas": "phosphorus_g",
        "Plastic": "plastic",
        "Plastium": "plastium",
        "Polluted Dirt": "polluted_dirt",
        "Polluted Ice": "polluted_ice",
        "Polluted Mud": "polluted_mud",
        "Polluted Oxygen": "polluted_oxygen",
        "Polluted Water": "polluted_water",
        "Propane Gas": "propane_g",
        "Pyrite": "pyrite",
        "Radium": "radium",
        "Refined Carbon": "refined_carbon",
        "Refined Phosphorus": "phosphorus_s",
        "Regolith": "regolith",
        "Rock Gas": "rock_gas",
        "Rust": "rust",
        "Salt Gas": "salt_g",
        "Salt Water": "salt_water",
        "Salt": "salt_s",
        "Sand": "sand",
        "Sandstone": "sandstone",
        "Sedimentary Rock": "sedimentary_rock",
        "Slime": "slime",
        "Snow": "snow",
        "Solid Carbon Dioxide": "carbon_dioxide_s",
        "Solid Chlorine": "chlorine_s",
        "Solid Crude Oil": "crude_oil_s",
        "Solid Ethanol": "ethanol_s",
        "Solid Hydrogen": "hydrogen_s",
        "Solid Methane": "methane_s",
        "Solid Naphtha": "naphtha_s",
        "Solid Nuclear Waste": "solid_nuclear_waste",
        "Solid Oxygen": "oxygen_s",
        "Solid Petroleum": "petroleum_s",
        "Solid Propane": "propane_s",
        "Solid Resin": "resin_s",
        "Solid Super Coolant": "super_coolant_s",
        "Solid Visco-Gel": "visco-gel_s",
        "Sour Gas": "sour_gas",
        "Steam": "steam",
        "Steel Gas": "steel_g",
        "Steel": "steel_s",
        "Sucrose": "sucrose_s",
        "Sulfur Gas": "sulfur_g",
        "Sulfur": "sulfur_s",
        "Super Coolant Gas": "super_coolant_g",
        "Super Coolant": "super_coolant_l",
        "Thermium": "thermium",
        "Tungsten Gas": "tungsten_g",
        "Tungsten": "tungsten_s",
        "Uranium Ore": "uranium_ore",
        "Visco-Gel Fluid": "visco-gel_l",
        "Water": "water",
        "Wolframite": "wolframite"
    },
    buildings: {
        "Algae Distiller": "algae_distiller",
        "Algae Terrarium": "algae_terrarium",
        "Ancient Specimen": "ancient_specimen",
        "Anti Entropy Thermo-Nullifier": "anti_entropy_thermo-nullifier",
        "Apothecary": "apothecary",
        "Biobot Builder": "biobot_builder",
        "Blastshot Maker": "blastshot_maker",
        "Bleach Stone Hopper": "bleach_stone_hopper",
        "Crafting Station": "crafting_station",
        "Desalinator": "desalinator",
        "Diamond Press": "diamond_press",
        "Electric Grill": "electric_grill",
        "Electrolyzer": "electrolyzer",
        "Ethanol Distiller": "ethanol_distiller",
        "Exosuit Forge": "exosuit_forge",
        "Fertilizer Synthetizer": "fertilizer_synthesizer",
        "Gas Range": "gas_range",
        "Glass Forge": "glass_forge",
        "Hand Sanitizer": "hand_sanitizer",
        "Hydrogen Generator": "hydrogen_generator",
        "Kiln": "kiln",
        "Metal Refinery": "metal_refinery",
        "Molecular Forge": "molecular_forge",
        "Oil Refinery": "oil_refinery",
        "Oil Well Cap": "oil_well_cap",
        "Ore Scrubber": "ore_scrubber",
        "Oxygen Diffuser": "oxygen_diffuser",
        "Oxylite Refinery": "oxylite_refinery",
        "Petroleum Generator": "petroleum_generator",
        "Polymer Press": "polymer_press",
        "Rock Crusher": "rock_crusher",
        "Rust Deoxidizer": "rust-deoxidizer",
        "Sludge Press": "sludge_press",
        "Sporechid": "sporechid",
        "Wood Burner": "wood_burner"
    },
    foods: {
        "barbeque": "barbeque",
        "berry_sludge": "berry_sludge",
        "bog_jelly": "bog_jelly",
        "bristle_berry": "bristle_berry",
        "cooked_seafood": "cooked_seafood",
        "curried_beans": "curried_beans",
        "fried_mushroom": "fried_mushroom",
        "frost_bun": "frost_bun",
        "frost_burger": "frost_burger",
        "gamma_mush": "gamma_mush",
        "gristle_berry": "gristle_berry",
        "grubfruit": "grubfruit",
        "grubfruit_preserve": "grubfruit_preserve",
        "hexalent_fruit": "hexalent_fruit",
        "lettuce": "lettuce",
        "liceloaf": "liceloaf",
        "meal_lice": "meal_lice",
        "meat": "meat",
        "mixed_berry_pie": "mixed_berry_pie",
        "muckroot": "muckroot",
        "mush_bar": "mush_bar",
        "mush_fry": "mush_fry",
        "mushroom": "mushroom",
        "mushroom_wrap": "mushroom_wrap",
        "nosh_bean": "nosh_bean",
        "nutrient_bar": "nutrient_bar",
        "omelette": "omelette",
        "pacu_fillet": "pacu_fillet",
        "pepper_bread": "pepper_bread",
        "pickled_meal": "pickled_meal",
        "pincha_peppernut": "pincha_peppernut",
        "plant_meat": "plant_meat",
        "raw_egg": "raw_egg",
        "raw_shellfish": "raw_shellfish",
        "roast_grubfruit_nut": "roast_grubfruit_nut",
        "sleet_wheat_seed": "sleet_wheat_seed",
        "spicy_tofu": "spicy_tofu",
        "spindly_grubfruit": "spindly_grubfruit",
        "stuffed_berry": "stuffed_berry",
        "surf'n'Turf": "surf'n'Turf",
        "swamp_chard_heart": "swamp_chard_heart",
        "swampy_delights": "swampy_delights",
        "tofu": "tofu",
    },
    critters: {
        "Abyss Bug": "abyss_bug",
        "Azure Bug": "azure_bug",
        "Beeta": "beeta",
        "Coral Bug": "coral_bug",
        "Cuddle Pip": "cuddle_pip",
        "Delecta Vole": "delecta_vole",
        "Dense Puft": "dense_puft",
        "Drecko": "drecko",
        "Gassy Moo": "gassy_moo",
        "Glossy Drecko": "glossy_drecko",
        "Grubgrub": "grubgrub",
        "Gulp Fish": "gulp_fish",
        "Hatch": "hatch",
        "Longhair Slicker": "longhair_slicker",
        "Molten Slicker": "molten_slicker",
        "Morb": "morb",
        "Oakshell": "oakshell",
        "Pacu": "pacu",
        "Pacu Tropical": "pacu_tropical",
        "Pip": "pip",
        "Plug Slug": "plug_slug",
        "Pokeshell": "pokeshell",
        "Puft": "puft",
        "Puft Prince": "puft_prince",
        "Radiant Bug": "radiant_bug",
        "Royal Bug": "royal_bug",
        "Sage Hatch": "sage_hatch",
        "Sanishell": "sanishell",
        "Shine Bug": "shine_bug",
        "Shove Vole": "shove_vole",
        "Slicker": "slicker",
        "Smog Plug": "smog_plug",
        "Smooth Hatch": "smooth_hatch",
        "Sponge Plug": "sponge_plug",
        "Squeaky Puft": "squeaku_puft",
        "Stone Hatch": "stone_hatch",
        "Sun Bug": "sun_bug",
        "Sun Nymph": "sun_nymph_egg",
        "Sweetle": "sweetle"
    },
    plants: {
        "arbor_tree": "arbor_tree",
        "arbor_tree_seed": "arbor_tree_seed",
        "balm_lily": "balm_lily",
        "balm_lily_seed": "balm_lily_seed",
        "bliss_burst_seed": "bliss_burst_seed",
        "bluff_briar_seed": "bluff_briar_seed",
        "bog_bucket_seed": "bog_bucket_seed",
        "bristle_blossom": "bristle_blossom",
        "bristle_blossom_seed": "bristle_blossom_seed",
        "buddy_bud_seed": "buddy_bud_seed",
        "buried_muckroot_seed": "buried_muckroot_seed",
        "dasha_saltvine": "dasha_saltvine",
        "dasha_saltvine_seed": "dasha_saltvine_seed",
        "dusk_cap": "dusk_cap",
        "dusk_cap_seed": "dusk_cap_seed",
        "gas_grass": "gas_grass",
        "gas_grass_seed": "gas_grass_seed",
        "grubfruit_plant": "grubfruit_plant",
        "hexalent_seed": "hexalent_seed",
        "hydrocactus": "hydrocactus",
        "hydrocactus_seed": "hydrocactus_seed",
        "jumping_joya_seed": "jumping_joya_seed",
        "mealwood": "mealwood",
        "mealwood_seed": "mealwood_seed",
        "mellow_mallow_seed": "mellow_mallow_seed",
        "mirth_leaf_seed": "mirth_leaf_seed",
        "nosh_sprout": "nosh_sprout",
        "nosh_sprout_seed": "nosh_sprout_seed",
        "oxyfern": "oxyfern",
        "oxyfern_seed": "oxyfern_seed",
        "pincha_pepperplant": "pincha_pepperplant",
        "pincha_pepperplant_seed": "pincha_pepperplant_seed",
        "saturn_critter_trap_seed": "saturn_critter_trap_seed",
        "sleet_wheat": "sleet_wheat",
        "sleet_wheat_seed": "sleet_wheat_seed",
        "spindly_grubfruit_plant_seed": "spindly_grubfruit_plant_seed",
        "sporechid": "sporechid",
        "sporechid_seed": "sporechid_seed",
        "swamp_chard_seed": "swamp_chard_seed",
        "thimble_reed": "thimble_reed",
        "thimble_reed_seed": "thimble_reed_seed",
        "tranquil_toes_seed": "tranquil_toes_seed",
        "waterweed": "waterweed",
        "waterweed_seed": "waterweed_seed",
        "wheezewort": "wheezewort",
        "wheezewort_seed": "wheezewort_seed",
    },
    geysers: {
        "aluminium_volcano": "aluminium_volcano",
        "carbon_dioxide_geyser": "carbon_dioxide_geyser",
        "carbon_dioxide_vent": "carbon_dioxide_vent",
        "chlorine_gas_vent": "chlorine_gas_vent",
        "cobalt_volcano": "cobalt_volcano",
        "cool_salt_slush_geyser": "cool_salt_slush_geyser",
        "cool_slush_geyser": "cool_slush_geyser",
        "cool_steam_vent": "cool_steam_vent",
        "copper_volcano": "copper_volcano",
        "gold_volcano": "gold_volcano",
        "hot_polluted_oxygen_vent": "hot_polluted_oxygen_vent",
        "hydrogen_vent": "hydrogen_vent",
        "infectious_polluted_oxygen_vent": "infectious_polluted_oxygen_vent",
        "iron_volcano": "iron_volcano",
        "leaky_oil_fissure": "leaky_oil_fissure",
        "liquid_sulfur_geyser": "liquid_sulfur_geyser",
        "minor_volcano": "minor_volcano",
        "natural_gas_geyser2": "natural_gas_geyser2",
        "natural_gas_geyser": "natural_gas_geyser",
        "niobium_volcano": "niobium_volcano",
        "polluted_water_vent": "polluted_water_vent",
        "salt_water_geyser": "salt_water_geyser",
        "steam_geyser": "steam_geyser",
        "steam_vent": "steam_vent",
        "tungsten_volcano": "tungsten_volcano",
        "volcano": "volcano",
        "water_geyser": "water_geyser"
    },
    planets: {
        "arid_planet": "arid_planet",
        "carbon_asteroid": "carbon_asteroid",
        "chlorine_planet": "chlorine_planet",
        "copper_comet": "copper_comet",
        "defunct_satellite": "defunct_satellite",
        "dust_comet": "dust_comet",
        "dusty_dwarf": "dusty_dwarf",
        "fullerene_comet": "fullerene_comet",
        "gas_giant": "gas_giant",
        "gassy_mooteor": "gassy_mooteor",
        "gilded_asteroid": "gilded_asteroid",
        "glimmering_planet": "glimmering_planet",
        "gold_comet": "gold_comet",
        "helium_giant": "helium_giant",
        "ice_giant": "ice_giant",
        "interstellar_ice": "interstellar_ice",
        "iron_comet": "iron_comet",
        "living_planet": "living_planet",
        "metalic_asteroid": "metalic_asteroid",
        "oily_asteriod": "oily_asteriod",
        "organic_mass": "organic_mass",
        "oxidized_asteroid": "oxidized_asteroid",
        "radioactive_comet": "radioactive_comet",
        "red_dwarf": "red_dwarf",
        "rock_comet": "rock_comet",
        "rocky_asteroid": "rocky_asteroid",
        "salty_dwarf": "salty_dwarf",
        "satellite": "satellite",
        "snack_bomb": "snack_bomb",
        "terrestrial_planet": "terrestrial_planet",
        "volcanic_planet": "volcanic_planet",
    },
    others: {
        "allergy_medication": "allergy_medication",
        "basic_rad_pill": "basic_rad_pill",
        "curative_tablet": "curative_tablet",
        "immuno_booster": "immuno_booster",
        "medical_pack": "medical_pack",
        "serum_vial": "serum_vial",
        "vitamin_chews": "vitamin_chews",
        "advanced_research": "advanced_research",
        "atmo_suit": "atmo_suit",
        "balm_lily_flower": "balm_lily_flower",
        "biobot.webp": "biobot.webp",
        "blastshot": "blastshot",
        "cool_vest": "cool_vest",
        "data_bank": "data_bank",
        "duplicant": "duplicant",
        "egg_shell": "egg_shell",
        "gas_grass": "gas_grass",
        "jet_suit": "jet_suit",
        "lead_suit": "lead_suit",
        "lumber": "lumber",
        "novice_research": "novice_research",
        "nuclear_research": "nuclear_research",
        "oakshell_molt": "oakshell_molt",
        "orbital_research": "orbital_research",
        "oxygen_mask": "oxygen_mask",
        "pokeshell_molt": "pokeshell_molt",
        "primo_garb": "primo_garb",
        "radbolts": "radbolts",
        "reed_fiber": "reed_fiber",
        "rot_pile": "rot_pile",
        "small_oakshell_molt": "small_oakshell_molt",
        "small_pokeshell_molt": "small_pokeshell_molt",
        "snazzy_suit": "snazzy_suit",
        "table_salt": "table_salt",
        "tonic_root": "tonic_root",
        "vacillator_recharge": "vacillator_recharge",
        "warm_sweater": "warm_sweater",
        "worn_atmo_suit": "worn_atmo_suit",
        "worn_jet_suit": "worn_jet_suit",
        "worn_lead_suit": "worn_lead_suit",
        "worn_oxygen_mask": "worn_oxygen_mask",
    }
}