img = {
    "critters": {
        "Abyss Bug": "abyss_bug",
        "Azure Bug": "azure_bug",
        "Beeta": "beeta",
        "Coral Bug": "coral_bug",
        "Cuddle Pip": "cuddle_pip",
        "Delecta Vole": "delecta_vole",
        "Dense Puft": "dense_puft",
        "Drecko": "drecko",
        "Gassy Moo": "gassy_moo",
        "Glossy Drecko": "glossy_drecko",
        "Grubgrub": "grubgrub",
        "Gulp Fish": "gulp_fish",
        "Hatch": "hatch",
        "Longhair Slicker": "longhair_slicker",
        "Molten Slicker": "molten_slicker",
        "Morb": "morb",
        "Oakshell": "oakshell",
        "Pacu": "pacu",
        "Pacu Tropical": "pacu_tropical",
        "Pip": "pip",
        "Plug Slug": "plug_slug",
        "Pokeshell": "pokeshell",
        "Puft": "puft",
        "Puft Prince": "puft_prince",
        "Radiant Bug": "radiant_bug",
        "Royal Bug": "royal_bug",
        "Sage Hatch": "sage_hatch",
        "Sanishell": "sanishell",
        "Shine Bug": "shine_bug",
        "Shove Vole": "shove_vole",
        "Slicker": "slicker",
        "Smog Plug": "smog_plug",
        "Smooth Hatch": "smooth_hatch",
        "Sponge Plug": "sponge_plug",
        "Squeaky Puft": "squeaku_puft",
        "Stone Hatch": "stone_hatch",
        "Sun Bug": "sun_bug",
        "Sun Nymph": "sun_nymph_egg",
        "Sweetle": "sweetle"
    },
    "elements": {
        "Abyssalite": "abyssalite",
        "Algae": "algae",
        "Aluminum Gas": "aluminum_g",
        "Aluminum Ore": "aluminum-ore",
        "Aluminum": "aluminum_s",
        "Bitumen": "bitumen",
        "Bleach Stone": "bleach_stone",
        "Brackene": "ice",
        "Brackwax": "brackwax",
        "Brine Ice": "brine_ice",
        "Brine": "brine",
        "Carbon Dioxide": "carbon_dioxide_g",
        "Carbon Gas": "carbon_g",
        "Ceramic": "ceramic",
        "Chlorine Gas": "chlorine_g",
        "Clay": "clay",
        "Coal": "coal",
        "Cobalt Gas": "cobalt_g",
        "Cobalt Ore": "cobalt-ore",
        "Cobalt": "cobalt_s",
        "Copper Gas": "copper_g",
        "Copper Ore": "copper-ore",
        "Copper": "copper_s",
        "Corium": "corium",
        "Crude Oil": "crude_oil_l",
        "Crushed Ice": "crushed_ice",
        "Crushed Rock": "crushed_rock",
        "Depleted Uranium": "depleted_uranium",
        "Diamond": "diamond",
        "Dirt": "dirt",
        "Electrum": "electrum",
        "Enriched Uranium": "enriched_uranium",
        "Ethanol Gas": "ethanol_g",
        "Ethanol": "ethanol_l",
        "Fertilizer": "fertilizer",
        "Fossil": "fossil",
        "Frozen Brackene": "ice",
        "Fullerene": "fullerene",
        "Genetic Ooze": "genetic_ooze",
        "Glass": "glass_s",
        "Gold Amalgam": "gold-amalgam",
        "Gold Gas": "gold_g",
        "Gold": "gold_s",
        "Granite": "granite",
        "Graphite": "graphite",
        "Hydrogen Gas": "hydrogen_g",
        "Ice": "ice",
        "Igneous Rock": "igneous_rock",
        "Insulite": "insulation",
        "Iron Gas": "iron_g",
        "Iron Ore": "iron-ore",
        "Iron": "iron_s",
        "Isoresin": "isoresin",
        "Lead Gas": "lead_g",
        "Lead": "lead_s",
        "Lime": "lime",
        "Liquid Carbon Dioxide": "carbon_dioxide_l",
        "Liquid Carbon": "carbon_l",
        "Liquid Chlorine": "chlorine_l",
        "Liquid Hydrogen": "hydrogen_l",
        "Liquid Methane": "methane_l",
        "Liquid Naphtha": "naphtha_l",
        "Liquid Nuclear Waste": "nuclear_waste",
        "Liquid Oxygen": "oxygen_l",
        "Liquid Phosphorus": "phosphorus_l",
        "Liquid Propane": "propane_l",
        "Liquid Resin": "resin_l",
        "Liquid Sucrose": "sucrose_l",
        "Liquid Sulfur": "liquid_sulfur",
        "Liquid Uranium": "uranium",
        "Mafic Rock": "mafic_rock",
        "Magma": "magma",
        "Molten Aluminum": "aluminum_l",
        "Molten Cobalt": "cobalt_l",
        "Molten Copper": "copper_l",
        "Molten Glass": "glass_l",
        "Molten Gold": "gold_l",
        "Molten Iron": "iron_l",
        "Molten Lead": "lead_l",
        "Molten Niobium": "niobium_l",
        "Molten Salt": "salt_l",
        "Molten Steel": "steel_l",
        "Molten Synthesis Gas": "",
        "Molten Tungsten": "tungsten_l",
        "Mud": "mud",
        "Natural Gas": "natural_gas",
        "Neutronium": "neutronium",
        "Niobium Gas": "niobium_g",
        "Niobium": "niobium_s",
        "Nuclear Fallout": "nuclear_fallout",
        "Obsidian": "obsidian",
        "Oxygen": "oxygen_g",
        "Oxylite": "oxylite",
        "Petroleum": "petroleum_l",
        "Phosphorite": "phosphorite",
        "Phosphorus Gas": "phosphorus_g",
        "Plastic": "plastic",
        "Plastium": "plastium",
        "Polluted Dirt": "polluted_dirt",
        "Polluted Ice": "polluted_ice",
        "Polluted Mud": "polluted_mud",
        "Polluted Oxygen": "polluted_oxygen",
        "Polluted Water": "polluted_water",
        "Propane Gas": "propane_g",
        "Pyrite": "pyrite",
        "Radium": "radium",
        "Refined Carbon": "refined_carbon",
        "Refined Phosphorus": "phosphorus_s",
        "Regolith": "regolith",
        "Rock Gas": "rock_gas",
        "Rust": "rust",
        "Salt Gas": "salt_g",
        "Salt Water": "salt_water",
        "Salt": "salt_s",
        "Sand": "sand",
        "Sandstone": "sandstone",
        "Sedimentary Rock": "sedimentary_rock",
        "Slime": "slime",
        "Snow": "snow",
        "Solid Carbon Dioxide": "carbon_dioxide_s",
        "Solid Chlorine": "chlorine_s",
        "Solid Crude Oil": "crude_oil_s",
        "Solid Ethanol": "ethanol_s",
        "Solid Hydrogen": "hydrogen_s",
        "Solid Methane": "methane_s",
        "Solid Naphtha": "naphtha_s",
        "Solid Nuclear Waste": "solid_nuclear_waste",
        "Solid Oxygen": "oxygen_s",
        "Solid Petroleum": "petroleum_s",
        "Solid Propane": "propane_s",
        "Solid Resin": "resin_s",
        "Solid Super Coolant": "super_coolant_s",
        "Solid Visco-Gel": "visco-gel_s",
        "Sour Gas": "sour_gas",
        "Steam": "steam",
        "Steel Gas": "steel_g",
        "Steel": "steel_s",
        "Sucrose": "sucrose_s",
        "Sulfur Gas": "sulfur_g",
        "Sulfur": "sulfur_s",
        "Super Coolant Gas": "super_coolant_g",
        "Super Coolant": "super_coolant_l",
        "Thermium": "thermium",
        "Tungsten Gas": "tungsten_g",
        "Tungsten": "tungsten_s",
        "Uranium Ore": "uranium_ore",
        "Visco-Gel Fluid": "visco-gel_l",
        "Water": "water",
        "Wolframite": "wolframite"
    }
}