img = {
    colors: {
        "element": "102 85 61",
        "building": "102 60 88",
        "food": "61 62 102",
        "critter": "102 63 61",
        "geyser": "91 102 94",
        "plant": "69 102 61",
        "planet": "99 102 61",
        "other": "61 102 97"
    },
    elements: {
        "Abyssalite": "abyssalite",
        "Algae": "algae",
        "Aluminum Gas": "aluminum_g",
        "Aluminum Ore": "aluminum-ore",
        "Aluminum": "aluminum_s",
        "Bitumen": "bitumen",
        "Bleach Stone": "bleach_stone",
        "Brackene": "ice",
        "Brackwax": "brackwax",
        "Brine Ice": "brine_ice",
        "Brine": "brine",
        "Carbon Dioxide": "carbon_dioxide_g",
        "Carbon Gas": "carbon_g",
        "Ceramic": "ceramic",
        "Chlorine Gas": "chlorine_g",
        "Clay": "clay",
        "Coal": "coal",
        "Cobalt Gas": "cobalt_g",
        "Cobalt Ore": "cobalt-ore",
        "Cobalt": "cobalt_s",
        "Copper Gas": "copper_g",
        "Copper Ore": "copper-ore",
        "Copper": "copper_s",
        "Corium": "corium",
        "Crude Oil": "crude_oil_l",
        "Crushed Ice": "crushed_ice",
        "Crushed Rock": "crushed_rock",
        "Depleted Uranium": "depleted_uranium",
        "Diamond": "diamond",
        "Dirt": "dirt",
        "Electrum": "electrum",
        "Enriched Uranium": "enriched_uranium",
        "Ethanol Gas": "ethanol_g",
        "Ethanol": "ethanol_l",
        "Fertilizer": "fertilizer",
        "Fossil": "fossil",
        "Frozen Brackene": "ice",
        "Fullerene": "fullerene",
        "Genetic Ooze": "genetic_ooze",
        "Glass": "glass_s",
        "Gold Amalgam": "gold-amalgam",
        "Gold Gas": "gold_g",
        "Gold": "gold_s",
        "Granite": "granite",
        "Graphite": "graphite",
        "Hydrogen Gas": "hydrogen_g",
        "Ice": "ice",
        "Igneous Rock": "igneous_rock",
        "Insulite": "insulation",
        "Iron Gas": "iron_g",
        "Iron Ore": "iron-ore",
        "Iron": "iron_s",
        "Isoresin": "isoresin",
        "Lead Gas": "lead_g",
        "Lead": "lead_s",
        "Lime": "lime",
        "Liquid Carbon Dioxide": "carbon_dioxide_l",
        "Liquid Carbon": "carbon_l",
        "Liquid Chlorine": "chlorine_l",
        "Liquid Hydrogen": "hydrogen_l",
        "Liquid Methane": "methane_l",
        "Liquid Naphtha": "naphtha_l",
        "Liquid Nuclear Waste": "nuclear_waste",
        "Liquid Oxygen": "oxygen_l",
        "Liquid Phosphorus": "phosphorus_l",
        "Liquid Propane": "propane_l",
        "Liquid Resin": "resin_l",
        "Liquid Sucrose": "sucrose_l",
        "Liquid Sulfur": "liquid_sulfur",
        "Liquid Uranium": "uranium",
        "Mafic Rock": "mafic_rock",
        "Magma": "magma",
        "Molten Aluminum": "aluminum_l",
        "Molten Cobalt": "cobalt_l",
        "Molten Copper": "copper_l",
        "Molten Glass": "glass_l",
        "Molten Gold": "gold_l",
        "Molten Iron": "iron_l",
        "Molten Lead": "lead_l",
        "Molten Niobium": "niobium_l",
        "Molten Salt": "salt_l",
        "Molten Steel": "steel_l",
        "Molten Synthesis Gas": "",
        "Molten Tungsten": "tungsten_l",
        "Mud": "mud",
        "Natural Gas": "natural_gas",
        "Neutronium": "neutronium",
        "Niobium Gas": "niobium_g",
        "Niobium": "niobium_s",
        "Nuclear Fallout": "nuclear_fallout",
        "Obsidian": "obsidian",
        "Oxygen": "oxygen_g",
        "Oxylite": "oxylite",
        "Petroleum": "petroleum_l",
        "Phosphorite": "phosphorite",
        "Phosphorus Gas": "phosphorus_g",
        "Plastic": "plastic",
        "Plastium": "plastium",
        "Polluted Dirt": "polluted_dirt",
        "Polluted Ice": "polluted_ice",
        "Polluted Mud": "polluted_mud",
        "Polluted Oxygen": "polluted_oxygen",
        "Polluted Water": "polluted_water",
        "Propane Gas": "propane_g",
        "Pyrite": "pyrite",
        "Radium": "radium",
        "Refined Carbon": "refined_carbon",
        "Refined Phosphorus": "phosphorus_s",
        "Regolith": "regolith",
        "Rock Gas": "rock_gas",
        "Rust": "rust",
        "Salt Gas": "salt_g",
        "Salt Water": "salt_water",
        "Salt": "salt_s",
        "Sand": "sand",
        "Sandstone": "sandstone",
        "Sedimentary Rock": "sedimentary_rock",
        "Slime": "slime",
        "Snow": "snow",
        "Solid Carbon Dioxide": "carbon_dioxide_s",
        "Solid Chlorine": "chlorine_s",
        "Solid Crude Oil": "crude_oil_s",
        "Solid Ethanol": "ethanol_s",
        "Solid Hydrogen": "hydrogen_s",
        "Solid Methane": "methane_s",
        "Solid Naphtha": "naphtha_s",
        "Solid Nuclear Waste": "solid_nuclear_waste",
        "Solid Oxygen": "oxygen_s",
        "Solid Petroleum": "petroleum_s",
        "Solid Propane": "propane_s",
        "Solid Resin": "resin_s",
        "Solid Super Coolant": "super_coolant_s",
        "Solid Visco-Gel": "visco-gel_s",
        "Sour Gas": "sour_gas",
        "Steam": "steam",
        "Steel Gas": "steel_g",
        "Steel": "steel_s",
        "Sucrose": "sucrose_s",
        "Sulfur Gas": "sulfur_g",
        "Sulfur": "sulfur_s",
        "Super Coolant Gas": "super_coolant_g",
        "Super Coolant": "super_coolant_l",
        "Thermium": "thermium",
        "Tungsten Gas": "tungsten_g",
        "Tungsten": "tungsten_s",
        "Uranium Ore": "uranium_ore",
        "Visco-Gel Fluid": "visco-gel_l",
        "Water": "water",
        "Wolframite": "wolframite"
    },
    buildings: {
        "Algae Distiller": "algae_distiller",
        "Algae Terrarium": "algae_terrarium",
        "Ancient Specimen": "ancient_specimen",
        "Anti Entropy Thermo-Nullifier": "anti_entropy_thermo-nullifier",
        "Apothecary": "apothecary",
        "Biobot Builder": "biobot_builder",
        "Blastshot Maker": "blastshot_maker",
        "Bleach Stone Hopper": "bleach_stone_hopper",
        "Crafting Station": "crafting_station",
        "Desalinator": "desalinator",
        "Diamond Press": "diamond_press",
        "Electric Grill": "electric_grill",
        "Electrolyzer": "electrolyzer",
        "Ethanol Distiller": "ethanol_distiller",
        "Exosuit Forge": "exosuit_forge",
        "Fertilizer Synthetizer": "fertilizer_synthesizer",
        "Gas Range": "gas_range",
        "Glass Forge": "glass_forge",
        "Hand Sanitizer": "hand_sanitizer",
        "Hydrogen Generator": "hydrogen_generator",
        "Kiln": "kiln",
        "Metal Refinery": "metal_refinery",
        "Molecular Forge": "molecular_forge",
        "Oil Refinery": "oil_refinery",
        "Oil Well Cap": "oil_well_cap",
        "Ore Scrubber": "ore_scrubber",
        "Oxygen Diffuser": "oxygen_diffuser",
        "Oxylite Refinery": "oxylite_refinery",
        "Petroleum Generator": "petroleum_generator",
        "Polymer Press": "polymer_press",
        "Rock Crusher": "rock_crusher",
        "Rust Deoxidizer": "rust-deoxidizer",
        "Sludge Press": "sludge_press",
        "Sporechid": "sporechid",
        "Wood Burner": "wood_burner"
    },
    foods: {
        "barbeque": "barbeque",
        "berry sludge": "berry_sludge",
        "bog jelly": "bog_jelly",
        "bristle berry": "bristle_berry",
        "cooked seafood": "cooked_seafood",
        "curried beans": "curried_beans",
        "fried mushroom": "fried_mushroom",
        "frost bun": "frost_bun",
        "frost burger": "frost_burger",
        "gamma mush": "gamma_mush",
        "gristle berry": "gristle_berry",
        "grubfruit": "grubfruit",
        "grubfruit preserve": "grubfruit_preserve",
        "hexalent fruit": "hexalent_fruit",
        "lettuce": "lettuce",
        "liceloaf": "liceloaf",
        "meal lice": "meal_lice",
        "meat": "meat",
        "mixed berry pie": "mixed_berry_pie",
        "muckroot": "muckroot",
        "mush bar": "mush_bar",
        "mush fry": "mush_fry",
        "mushroom": "mushroom",
        "mushroom wrap": "mushroom_wrap",
        "nosh bean": "nosh_bean",
        "nutrient bar": "nutrient_bar",
        "omelette": "omelette",
        "pacu fillet": "pacu_fillet",
        "pepper bread": "pepper_bread",
        "pickled meal": "pickled_meal",
        "pincha peppernut": "pincha_peppernut",
        "plant meat": "plant_meat",
        "raw egg": "raw_egg",
        "raw shellfish": "raw_shellfish",
        "roast grubfruit nut": "roast_grubfruit_nut",
        "sleet wheat seed": "sleet_wheat_seed",
        "spicy tofu": "spicy_tofu",
        "spindly grubfruit": "spindly_grubfruit",
        "stuffed berry": "stuffed_berry",
        "surf'n'Turf": "surf'n'Turf",
        "swamp chard heart": "swamp_chard_heart",
        "swampy delights": "swampy_delights",
        "tofu": "tofu",
    },
    critters: {
        "Abyss Bug": "abyss_bug",
        "Azure Bug": "azure_bug",
        "Beeta": "beeta",
        "Coral Bug": "coral_bug",
        "Cuddle Pip": "cuddle_pip",
        "Delecta Vole": "delecta_vole",
        "Dense Puft": "dense_puft",
        "Drecko": "drecko",
        "Gassy Moo": "gassy_moo",
        "Glossy Drecko": "glossy_drecko",
        "Grubgrub": "grubgrub",
        "Gulp Fish": "gulp_fish",
        "Hatch": "hatch",
        "Longhair Slicker": "longhair_slicker",
        "Molten Slicker": "molten_slicker",
        "Morb": "morb",
        "Oakshell": "oakshell",
        "Pacu": "pacu",
        "Pacu Tropical": "pacu_tropical",
        "Pip": "pip",
        "Plug Slug": "plug_slug",
        "Pokeshell": "pokeshell",
        "Puft": "puft",
        "Puft Prince": "puft_prince",
        "Radiant Bug": "radiant_bug",
        "Royal Bug": "royal_bug",
        "Sage Hatch": "sage_hatch",
        "Sanishell": "sanishell",
        "Shine Bug": "shine_bug",
        "Shove Vole": "shove_vole",
        "Slicker": "slicker",
        "Smog Plug": "smog_plug",
        "Smooth Hatch": "smooth_hatch",
        "Sponge Plug": "sponge_plug",
        "Squeaky Puft": "squeaku_puft",
        "Stone Hatch": "stone_hatch",
        "Sun Bug": "sun_bug",
        "Sun Nymph": "sun_nymph_egg",
        "Sweetle": "sweetle"
    },
    plants: {
        "arbor tree": "arbor_tree",
        "arbor tree seed": "arbor_tree_seed",
        "balm lily": "balm_lily",
        "balm lily seed": "balm_lily_seed",
        "bliss burst seed": "bliss_burst_seed",
        "bluff briar seed": "bluff_briar_seed",
        "bog bucket seed": "bog_bucket_seed",
        "bristle blossom": "bristle_blossom",
        "bristle blossom seed": "bristle_blossom_seed",
        "buddy bud seed": "buddy_bud_seed",
        "buried muckroot seed": "buried_muckroot_seed",
        "dasha saltvine": "dasha_saltvine",
        "dasha saltvine seed": "dasha_saltvine_seed",
        "dusk cap": "dusk_cap",
        "dusk cap seed": "dusk_cap_seed",
        "gas grass": "gas_grass",
        "gas grass seed": "gas_grass_seed",
        "grubfruit plant": "grubfruit_plant",
        "hexalent seed": "hexalent_seed",
        "hydrocactus": "hydrocactus",
        "hydrocactus seed": "hydrocactus_seed",
        "jumping joya seed": "jumping_joya_seed",
        "mealwood": "mealwood",
        "mealwood seed": "mealwood_seed",
        "mellow mallow seed": "mellow_mallow_seed",
        "mirth leaf seed": "mirth_leaf_seed",
        "nosh sprout": "nosh_sprout",
        "nosh sprout seed": "nosh_sprout_seed",
        "oxyfern": "oxyfern",
        "oxyfern seed": "oxyfern_seed",
        "pincha pepperplant": "pincha_pepperplant",
        "pincha pepperplant seed": "pincha_pepperplant_seed",
        "saturn critter trap seed": "saturn_critter_trap_seed",
        "sleet wheat": "sleet_wheat",
        "sleet wheat seed": "sleet_wheat_seed",
        "spindly grubfruit plant seed": "spindly_grubfruit_plant_seed",
        "sporechid": "sporechid",
        "sporechid seed": "sporechid_seed",
        "swamp chard seed": "swamp_chard_seed",
        "thimble reed": "thimble_reed",
        "thimble reed seed": "thimble_reed_seed",
        "tranquil toes seed": "tranquil_toes_seed",
        "waterweed": "waterweed",
        "waterweed seed": "waterweed_seed",
        "wheezewort": "wheezewort",
        "wheezewort seed": "wheezewort_seed",
    },
    geysers: {
        "aluminium volcano": "aluminium_volcano",
        "carbon dioxide geyser": "carbon_dioxide_geyser",
        "carbon dioxide vent": "carbon_dioxide_vent",
        "chlorine gas vent": "chlorine_gas_vent",
        "cobalt volcano": "cobalt_volcano",
        "cool salt slush geyser": "cool_salt_slush_geyser",
        "cool slush geyser": "cool_slush_geyser",
        "cool steam vent": "cool_steam_vent",
        "copper volcano": "copper_volcano",
        "gold volcano": "gold_volcano",
        "hot polluted oxygen vent": "hot_polluted_oxygen_vent",
        "hydrogen vent": "hydrogen_vent",
        "infectious polluted oxygen vent": "infectious_polluted_oxygen_vent",
        "iron volcano": "iron_volcano",
        "leaky oil fissure": "leaky_oil_fissure",
        "liquid sulfur geyser": "liquid_sulfur_geyser",
        "minor volcano": "minor_volcano",
        "natural gas geyser2": "natural_gas_geyser2",
        "natural gas geyser": "natural_gas_geyser",
        "niobium volcano": "niobium_volcano",
        "polluted water vent": "polluted_water_vent",
        "salt water geyser": "salt_water_geyser",
        "steam geyser": "steam_geyser",
        "steam vent": "steam_vent",
        "tungsten volcano": "tungsten_volcano",
        "volcano": "volcano",
        "water geyser": "water_geyser"
    },
    planets: {
        "arid planet": "arid_planet",
        "carbon asteroid": "carbon_asteroid",
        "chlorine planet": "chlorine_planet",
        "copper comet": "copper_comet",
        "defunct satellite": "defunct_satellite",
        "dust comet": "dust_comet",
        "dusty dwarf": "dusty_dwarf",
        "fullerene comet": "fullerene_comet",
        "gas giant": "gas_giant",
        "gassy mooteor": "gassy_mooteor",
        "gilded asteroid": "gilded_asteroid",
        "glimmering planet": "glimmering_planet",
        "gold comet": "gold_comet",
        "helium giant": "helium_giant",
        "ice giant": "ice_giant",
        "interstellar ice": "interstellar_ice",
        "iron comet": "iron_comet",
        "living planet": "living_planet",
        "metalic asteroid": "metalic_asteroid",
        "oily asteriod": "oily_asteriod",
        "organic mass": "organic_mass",
        "oxidized asteroid": "oxidized_asteroid",
        "radioactive comet": "radioactive_comet",
        "red dwarf": "red_dwarf",
        "rock comet": "rock_comet",
        "rocky asteroid": "rocky_asteroid",
        "salty dwarf": "salty_dwarf",
        "satellite": "satellite",
        "snack bomb": "snack_bomb",
        "terrestrial planet": "terrestrial_planet",
        "volcanic planet": "volcanic_planet",
    },
    others: {
        "allergy medication": "allergy_medication",
        "basic rad pill": "basic_rad_pill",
        "curative tablet": "curative_tablet",
        "immuno booster": "immuno_booster",
        "medical pack": "medical_pack",
        "serum vial": "serum_vial",
        "vitamin chews": "vitamin_chews",
        "advanced research": "advanced_research",
        "atmo suit": "atmo_suit",
        "balm lily flower": "balm_lily_flower",
        "biobot.webp": "biobot.webp",
        "blastshot": "blastshot",
        "cool vest": "cool_vest",
        "data bank": "data_bank",
        "duplicant": "duplicant",
        "egg shell": "egg_shell",
        "gas grass": "gas_grass",
        "jet suit": "jet_suit",
        "lead suit": "lead_suit",
        "lumber": "lumber",
        "novice research": "novice_research",
        "nuclear research": "nuclear_research",
        "oakshell molt": "oakshell_molt",
        "orbital research": "orbital_research",
        "oxygen mask": "oxygen_mask",
        "pokeshell molt": "pokeshell_molt",
        "primo garb": "primo_garb",
        "radbolts": "radbolts",
        "reed fiber": "reed_fiber",
        "rot pile": "rot_pile",
        "small oakshell molt": "small_oakshell_molt",
        "small pokeshell molt": "small_pokeshell_molt",
        "snazzy suit": "snazzy_suit",
        "table salt": "table_salt",
        "tonic root": "tonic_root",
        "vacillator recharge": "vacillator_recharge",
        "warm sweater": "warm_sweater",
        "worn atmo suit": "worn_atmo_suit",
        "worn jet suit": "worn_jet_suit",
        "worn lead suit": "worn_lead_suit",
        "worn oxygen mask": "worn_oxygen_mask",
    }
}